### ISSUE TITLE
annotations not showing when using multiple steps of action-flake8

### ISSUE THREAD

**Issue by laureanorp** [reviewdog/action-flake8#31]
Hello! I've configured this action for a project and we are adding checks slowly. For example, we check for W605 on the whole project:

```
  - name: flake8 W605 on project
    uses: reviewdog/action-flake8@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      flake8_args: --select=W605
      reporter: github-check
      filter_mode: nofilter
```

This works flawlessly.
But now that I want to add a new rule/flake8 code (W292), it's not working:

  ```
- name: flake8 W605, W292 on project
    uses: reviewdog/action-flake8@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      flake8_args: --select=W605,W292
      reporter: github-check
      filter_mode: nofilter
```

Note the `flake8_args: --select=W605,W292`. The action won't detect W292 neither W605. I have also tried with `flake8_args: --select=W605, W292` and `flake8_args: --select=W605, --select=W292`. Always 0 findings.

Of course, using two separate actions for both error codes work, the findings appear, but it's far from a perfect solution.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/14150766/139227213-a83da9da-bebf-4733-9aa1-0ef7008e0ba4.png">

What's the correct way to include a list of errors in `--select`?
