### ISSUE TITLE
reviewdog is not commenting on pull requests

### ISSUE THREAD

**Issue by d3cryptofc** [reviewdog/action-flake8#58]
why? I can only see the reports by opening the github actions tab, but it doesn't comment anything in the reviews

**NOTES:**
- I'm testing it in a private repository.

**FILE: `.github/workflows/reviewdog.yml`**
```yml
name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      # Install specific flake8 version (this step is not required. Default is "latest").
      - run: pip install flake8==6.0.0
      # Install flake8 extensions (this step is not required. Default is "None").
      - run: pip install flake8-docstrings flake8-simplify flake8-unused-arguments flake8-quotes
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
